application: money-stew
version: 3
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: img/
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /ledger/json.*
  script: ledger.py
- url: /test/.*
  script: test.py
- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
- url: /static
  static_dir: static
- url: /home
  script: app.py
- url: /app
  script: app.py
- url: /.*
  script: app.py


