application: money-stew
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /ledger/json.*
  script: ledger.py
- url: /test/.*
  script: test.py
- url: /.*
  script: asklogin.py

